tracts: [4850]
patches: ['4,4', '4,5']
filters: ["g", "r", "i", "z", "y"]
repo: /global/cscratch1/sd/desc/DC2/global/in2p3/Run1.1/output

medsdm_conf:
  class: File
  path: medsdm_config.yaml

ngmixit_conf:
  class: File
  path: run-dbcoadd-cm-001.yaml

output_filename: ngmix_catalog.fits

# Template name for output of ngmixit
tmp_ngmix_filename: tmp_ngmix.fits
